
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-cayman
gfm_quirks: paragraph_end

collections:
  designs:
    output: true
    permalink: /:title

title: France-IOI
description: Commented designs
github-url: https://github.com/France-ioi/algorea-designs
